---
- name: delpoy docker with docker compose
  hosts: all
  tasks:

    - name: Create a project if it does not exist
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Copy .env to project dir
      ansible.builtin.copy:
        src: ../.env
        dest: "{{ project_dir }}/.env"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0744'

    - name: Copy docker-compose.yaml to project dir
      ansible.builtin.copy:
        src: ../docker-compose.yaml
        dest: "{{ project_dir }}/docker-compose.yaml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0744'

    - name: Create and start services
      become: false                     #因為全域環境ansible.cfg有設定become: true，這邊不適合使用
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
      register: output


    - name: print status
      ansible.builtin.debug:
        var:  output
